'use client';
import { useEffect, useState } from 'react';
import { CalendarDays, Clock3, CheckCircle2 } from 'lucide-react';
type Slot={hour:string,available:boolean};
function dates() {
  const result:{key:string,label:string,weekday:string}[]=[];
  const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Amsterdam',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));
  const base=new Date(`${parts.year}-${parts.month}-${parts.day}T12:00:00Z`);
  for(let i=0;i<=14;i++){const d=new Date(base.getTime()+i*86400000);if([0,6].includes(d.getUTCDay()))continue;result.push({key:d.toISOString().slice(0,10),label:new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',timeZone:'UTC'}).format(d),weekday:new Intl.DateTimeFormat('nl-NL',{weekday:'short',timeZone:'UTC'}).format(d)});}
  return result;
}
export default function Home(){
 const days=dates(); const [day,setDay]=useState(days[0]?.key??'');const [slots,setSlots]=useState<Slot[]>([]);const [hour,setHour]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [result,setResult]=useState<{day:string,hour:string,name:string,cancelUrl:string}|null>(null);
 useEffect(()=>{let alive=true;setLoading(true);setError('');setHour('');fetch(`/api/slots?day=${day}`).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);if(alive)setSlots(x.slots);}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[day]);
 async function book(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const form=new FormData(e.currentTarget);try{const response=await fetch('/api/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({day,hour,name:form.get('name'),email:form.get('email')})});const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data);}catch(e){setError(e instanceof Error?e.message:'Er ging iets mis.');if(day){fetch(`/api/slots?day=${day}`).then(r=>r.json()).then(d=>setSlots(d.slots??[])).catch(()=>{});}}finally{setSaving(false)}}
 return <main className="shell"><header className="top"><div className="brand"><span className="brandmark"><CalendarDays size={21}/></span><span>Reserveren</span></div><span className="topnote">Afspraken op werkdagen</span></header><div className="content"><section className="intro"><div className="eyebrow">AGENDA</div><h1>Kies een moment<br/>dat je uitkomt.</h1><p>Plan een afspraak van een uur. Beschikbaar van maandag tot en met vrijdag, tussen 09.00 en 17.00 uur.</p><div className="info"><Clock3 size={19}/><span>Boek tot twee weken vooruit</span></div></section><section className="panel" aria-label="Reservering maken">{result?<div className="success"><CheckCircle2 size={34}/><h2>Afspraak gereserveerd</h2><p>{result.name}, je afspraak staat op {new Intl.DateTimeFormat('nl-NL',{dateStyle:'full',timeZone:'UTC'}).format(new Date(result.day+'T12:00:00Z'))} om {result.hour} uur.</p><div className="notice"><strong>Bewaar deze annuleringslink.</strong><p>Er wordt in deze versie nog geen e-mail verstuurd. Alleen met deze link kun je de afspraak annuleren.</p><a href={result.cancelUrl}>{result.cancelUrl}</a><button type="button" onClick={()=>navigator.clipboard.writeText(result.cancelUrl)}>Kopieer link</button></div><button className="secondary" onClick={()=>{setResult(null);location.reload()}}>Nieuwe reservering</button></div>:<><div className="step"><span>01</span><h2>Kies een dag</h2></div><div className="days">{days.map(d=><button key={d.key} type="button" className={day===d.key?'selected':''} onClick={()=>setDay(d.key)} aria-pressed={day===d.key}><small>{d.weekday}</small><strong>{d.label}</strong></button>)}</div><div className="step"><span>02</span><h2>Kies een tijd</h2></div>{loading?<p className="muted">Beschikbaarheid laden…</p>:<div className="slots">{slots.map(s=><button type="button" key={s.hour} disabled={!s.available} className={hour===s.hour?'selected':''} onClick={()=>setHour(s.hour)} aria-pressed={hour===s.hour}>{s.hour}</button>)}</div>}<div className="step details"><span>03</span><h2>Jouw gegevens</h2></div><form onSubmit={book}><div className="fields"><label>Naam<input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="Je naam"/></label><label>E-mailadres<input name="email" type="email" autoComplete="email" required placeholder="naam@voorbeeld.nl"/></label></div>{error&&<p className="error" role="alert">{error}</p>}<button className="submit" disabled={!hour||saving||loading}>{saving?'Reserveren…':'Reserveer afspraak'}</button></form></>}</section></div></main>
}
